name: Hello World
on: [push]
jobs:
  ouput_hello_world:
    name: Output Hello world
    runs-on: ubunto-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a script
      run: echo "Hello, World!"
